# Troubleshooting:
#     In case there is an error when installing sklearn: run pip install
#        Cython==0.29.23 manually and then run the above command again.
#     In case you have access to a GPU, see instructions [here]
#        (https://github.com/google/jax#pip-installation-gpu-cuda) for installing
#        the GPU version of jaxlib. This will make the experiment run
#        significantly faster.
name: fsvi
channels:
- defaults
- conda-forge
- anaconda
- pytorch
dependencies:
- python==3.10
- pillow
- pip==24.0
- psutil
- seaborn==0.13.2
- tabulate==0.9.0
- tqdm==4.66.4
- pytorch===2.3.1
- torchvision==0.18.1
- urllib3==2.2.2
- pip:
  - -i https://mirrors.sustech.edu.cn/pypi/web/simple
  - chex==0.1.7
  - dm-haiku==0.0.5
  - dm-sonnet==2.0.2
  - dm-tree==0.1.6
  - gpflow==2.2.1
  - gpustat==0.6.0
  - jax[cuda12]==0.4.23
  - joypy
  - keras==2.15.0
  - latex==0.7.0
  - neural-tangents==0.6.5
  - numpy==1.26.4
  - optax==0.2.0
  - pandas==1.3.5
  - pyreadr
  - pytest
  - retry==0.9.2
  - scikit-learn==1.5.0
  - scipy==1.12.0
  - seqtools==1.4.1
  - tensorflow==2.15.1
  - tensorflow-addons==0.23.0
  - tensorflow-datasets==4.2.0
  - tensorflow-probability==0.23.0
  - tf_keras
  - uncertainty-metrics==0.0.81
